server:
  port: ${SERVICE_PORT:8081}
management:
  endpoints:
    web:
      exposure:
        include: health, info, env
  security:
    enabled: 'false'
spring:
  datasource:
    password: asdert1233.
    username: postgres
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/pm25?currentSchema=public&stringtype=unspecified
  liquibase:
    change-log: classpath:db/db.changelog-master.xml
    password: asdert1233.
    user: postgres
    enabled: 'true'
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: 'false'
        show_sql: 'false'
service:
  yandex:
    static-maps-uri: https://static-maps.yandex.ru/1.x/
    api-key: f929862e-eb68-41c5-80b9-f4e118e03687
  osm:
    prod-api-uri: https://api.openstreetmap.org/
    dev-api-uri: https://master.apis.dev.openstreetmap.org/
  aqicn:
    uri: https://airnet.waqi.info/airnet/map/bounds
  iqair:
    uri: https://website-api.airvisual.com/v1/places/map/clusters?bbox=75.94,43.02,77.92,43.49&zoomLevel=6&units.temperature=celsius&units.distance=kilometer&units.pressure=millibar&units.system=metric&AQI=US&language=ru
